### ISSUE TITLE
Correct version of the specification

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-cat30#20]
When the development of the test started the following specifications were used:
- OGC 12-176r5 OGC Catalogue Services 3.0 Specification – HTTP Protocol Binding
- OGC 12-168r5 Catalog Services Specification 3.0 – General Model
- OGC 14-014r3 OGC Catalogue Services 3.0 Specification – HTTP Protocol Binding – Abstract Test Suite
- OGC 10-032r8 OGC OpenSearch Geo and Time Extensions, Version 1.0

The above references are the ones we used in the description of the test (welcome page).

I see we have now:
- 12-176r7
- 12-168r6

Is the latest revision of the test aligned with the latest revision of the standard?

And, we need to confirm that the test is implementing the following "implementable" standard:
OGC Catalogue Services 3.0 Specification - HTTP Protocol Binding

**Comment by rjmartell** [comment]
The last (pre-)release occurred in Oct 2015 and there have been no commits since. The final OGC specifications were approved several months later, so the tests may not be aligned with these depending on how many changes accrued between 12-176r5 (last revision: 2014-12-02) and 12-176r7 (approved: 2016-02-29) . A comparison should reveal this and indicate which changes--if any--are required to achieve alignment.

The test suite does indeed target the HTTP binding.

**Comment by bermud** [comment]
@Keshav, please compare this spec  http://docs.opengeospatial.org/is/12-176r7/12-176r7.html with the current test.

**Comment by keshav-nangare** [comment]
We have compare both specification document given below:

1.  http://docs.opengeospatial.org/is/12-176r7/12-176r7.html 

2. [12-176r6_OGC_Catalogue_Services_3.0_Specification_-_HTTP_Protocol_Binding.docx](https://github.com/opengeospatial/ets-cat30/files/595662/12-176r6_OGC_Catalogue_Services_3.0_Specification_-_HTTP_Protocol_Binding.docx)

The latest updated document(12-176r7) contains the same Test/ Requirements in the old spec document(12-176r6).

We have compared the test of the two conformance classes 1. Basic-Catalogue  2. OpenSearch, so both are class contains the same tests.

**Comment by bermud** [comment]
@keshav-nangare, Thank you!
