### ISSUE TITLE
How are csw:AnyText rules defined?

### ISSUE THREAD

**Issue by mhogeweg** [opengeospatial/ets-cat30#3]
the scope and semantics of csw:AnyText syntax in CSW 3.0 needs to be defined:
- phrase vs keyword
- grouping of phrases
- boolean logic
- ...

**Comment by rjmartell** [comment]
The AnyText "pseudo-property" is beyond the scope of tests for the `Basic` and `OpenSearch` conformance classes currently under development. However, it may be that the same constraints should apply to basic KVP text searches using the 'q' query parameter (Table 6: KVP encoding for query constraints).

__Requirement-030__ stipulates that the domain of AnyText is "all text fields in the catalogue record". Now, OGC 10-032r8 (_OGC OpenSearch Geo and Time Extensions_) suggests (see Table 4) that searchTerms be matched against the content of the following record elements:

* dc:title, atom:title 
* dc:description (dct:abstract), atom:summary 
* dc:subject, atom:category 

Since this is a normative reference, should this restriction apply to all basic text searches even though the CSW3 spec imposes fewer restrictions on the scope of AnyText for "advanced" queries (i.e. Filter-FES-KVP-Advanced)?

**Comment by rjmartell** [comment]
None of the relevant specs appear to have anything to say about:

1. Case sensitivity of matching;
2. Handling of multiple terms (e.g. treat them as a phrase or as separate terms with some implied boolean operator).

I suggest doing the the following for basic text searches: 

1. Matching is case-insensitive.
2. Treat multiple terms as a phrase (e.g. "San Francisco")

**Comment by rjmartell** [comment]
Then again, consider how search terms are [interpreted by the Google search engine](http://www.googleguide.com/interpreting_queries.html). Multiple terms are combined by an implicit AND operator.

Perhaps this would be sensible default behavior in keeping with the [POLA](http://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by rjmartell** [comment]
Basic text search using the `q` parameter is expected to be processed as follows:

* match against all record fields with simple content
* matching is case-insensitive
* multiple terms are combined by an implicit AND

Perhaps "advanced" text search using `csw:AnyText` will enable more complex queries.

**Comment by pvretano** [comment]
Table 6 in the CSW 3.0 specification has been updated to reflect the semantic described herein.  ie:
 Basic text search using the q parameter is expected to be processed as follows:
    match against all record fields with simple content
    matching is case-insensitive
    multiple terms are combined by an implicit AND

**Comment by mhogeweg** [comment]
The update to the spec is good (it makes it more explicit). The test needs to be updated as well, since what is returned in the response (brief, summary, …) may not include all of the record fields with simple content. The test can therefore not fail a response if that response did not include one of the terms provided in the request.
